/* TIBLY:SQL
CREATE TABLE IF NOT EXISTS ce_customer_profiles (
  visitor_id text PRIMARY KEY DEFAULT auth.user_id(),
  full_name text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  company text NOT NULL DEFAULT '',
  service_address text NOT NULL DEFAULT '',
  city text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT '',
  postal_code text NOT NULL DEFAULT '',
  preferred_contact text NOT NULL DEFAULT 'phone',
  site_access text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ce_service_calls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id text NOT NULL DEFAULT auth.user_id(),
  service_type text NOT NULL,
  site_address text NOT NULL DEFAULT '',
  preferred_date date,
  time_window text NOT NULL DEFAULT 'morning',
  urgency text NOT NULL DEFAULT 'standard',
  details text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'requested',
  technician text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ce_service_calls_visitor_idx ON ce_service_calls (visitor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS ce_projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id text NOT NULL DEFAULT auth.user_id(),
  name text NOT NULL,
  site_address text NOT NULL DEFAULT '',
  scope text NOT NULL DEFAULT '',
  phase text NOT NULL DEFAULT 'estimate requested',
  square_footage integer,
  target_start date,
  project_manager text NOT NULL DEFAULT 'Unassigned',
  budget_estimate numeric(12,2),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ce_projects_visitor_idx ON ce_projects (visitor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS ce_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id text NOT NULL DEFAULT auth.user_id(),
  item_sku text NOT NULL,
  item_name text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric(10,2) NOT NULL DEFAULT 0,
  install_address text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'received',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ce_orders_visitor_idx ON ce_orders (visitor_id, created_at DESC);

ALTER TABLE ce_customer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE ce_service_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE ce_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE ce_orders ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN CREATE POLICY ce_profiles_sel ON ce_customer_profiles FOR SELECT TO authenticated USING (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY ce_profiles_ins ON ce_customer_profiles FOR INSERT TO authenticated WITH CHECK (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY ce_profiles_upd ON ce_customer_profiles FOR UPDATE TO authenticated USING (visitor_id = auth.user_id()) WITH CHECK (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE POLICY ce_calls_sel ON ce_service_calls FOR SELECT TO authenticated USING (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY ce_calls_ins ON ce_service_calls FOR INSERT TO authenticated WITH CHECK (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY ce_calls_del ON ce_service_calls FOR DELETE TO authenticated USING (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE POLICY ce_projects_sel ON ce_projects FOR SELECT TO authenticated USING (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY ce_projects_ins ON ce_projects FOR INSERT TO authenticated WITH CHECK (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE POLICY ce_orders_sel ON ce_orders FOR SELECT TO authenticated USING (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY ce_orders_ins ON ce_orders FOR INSERT TO authenticated WITH CHECK (visitor_id = auth.user_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

GRANT SELECT, INSERT, UPDATE ON ce_customer_profiles TO anonymous, authenticated;
GRANT SELECT, INSERT, DELETE ON ce_service_calls TO anonymous, authenticated;
GRANT SELECT, INSERT ON ce_projects TO anonymous, authenticated;
GRANT SELECT, INSERT ON ce_orders TO anonymous, authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anonymous, authenticated;
*/
import React, { useCallback, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { NeonPostgrestClient } from "@neondatabase/postgrest-js";
import { createAuthClient } from "@neondatabase/auth";

const TB: any = (window as any).TIBLY_BACKEND || {};
const auth: any = createAuthClient(TB.authUrl);

const INPUT = "w-full rounded-lg border border-ink/15 bg-white px-3 py-2 text-sm text-ink focus:border-brand-600 focus:outline-none";
const LABEL = "block text-xs font-semibold uppercase tracking-wide text-ink/60 mb-1";

type Call = { id: number; service_type: string; site_address: string; preferred_date: string | null; time_window: string; urgency: string; details: string; status: string; technician: string; created_at: string };
type Project = { id: number; name: string; site_address: string; scope: string; phase: string; square_footage: number | null; target_start: string | null; project_manager: string; budget_estimate: any; created_at: string };
type Order = { id: number; item_sku: string; item_name: string; quantity: number; unit_price: any; install_address: string; status: string; created_at: string };
type Profile = { visitor_id: string; full_name: string; email: string; phone: string; company: string; service_address: string; city: string; state: string; postal_code: string; preferred_contact: string; site_access: string };

const CATALOG = [
  { sku: "SURGE-WH", name: "Whole-building surge protection", price: 685, blurb: "Type 2 device at the service panel, torque-checked and labeled." },
  { sku: "EVSE-L2", name: "Level 2 EV charger install", price: 1290, blurb: "60A circuit, hardwired unit, load calc included." },
  { sku: "PANEL-200", name: "200A service and panel upgrade", price: 2850, blurb: "New meter main, permit and utility coordination handled." },
  { sku: "GEN-22", name: "22kW standby generator install", price: 1450, blurb: "Pad, transfer switch and startup. Deposit price shown." },
  { sku: "LED-RETRO", name: "LED retrofit, per fixture", price: 145, blurb: "Commercial troffer and high bay swaps, disposal included." },
  { sku: "EM-INSPECT", name: "Emergency lighting inspection", price: 395, blurb: "Annual 90 minute test with signed documentation." }
];

function friendly(e: any): string {
  const m = String((e && e.message) || e || "");
  if (/relation|does not exist|schema cache|permission denied/i.test(m)) return "This page isn't fully set up yet. Wait a moment and refresh.";
  if (/fetch|network|failed/i.test(m)) return "We couldn't reach the server. Check your connection and try again.";
  return m || "Something went wrong.";
}

async function freshToken(): Promise<string | null> {
  try {
    const r = await fetch(TB.authUrl + "/token", { credentials: "include" });
    if (!r.ok) return null;
    const j = await r.json();
    return j && j.token ? j.token : null;
  } catch { return null; }
}

async function db(): Promise<any> {
  const token = await freshToken();
  if (!token) throw new Error("Your session ended. Please sign in again.");
  return new NeonPostgrestClient({ dataApiUrl: TB.dataApiUrl, options: { global: { headers: { Authorization: "Bearer " + token } } } });
}

function money(v: any): string { const n = Number(v) || 0; return "$" + n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function day(v: string | null): string { if (!v) return "To be scheduled"; const d = new Date(v.length <= 10 ? v + "T12:00:00" : v); return isNaN(d.getTime()) ? String(v) : d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }

function Badge({ text }: { text: string }) {
  const t = text.toLowerCase();
  const cls = t.includes("complete") || t.includes("closed") ? "bg-emerald-100 text-emerald-800"
    : t.includes("schedul") || t.includes("progress") || t.includes("route") ? "bg-blue-100 text-blue-800"
    : t.includes("hold") || t.includes("wait") ? "bg-amber-100 text-amber-900"
    : "bg-ink/10 text-ink";
  return <span className={"inline-block rounded-full px-3 py-1 text-xs font-semibold capitalize " + cls}>{text}</span>;
}

function SignIn() {
  const [email, setEmail] = useState("");
  const [pw, setPw] = useState("");
  const [sent, setSent] = useState(false);
  const [fallback, setFallback] = useState(false);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");

  async function magic(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setErr("");
    try {
      await auth.signIn.magicLink({ email, callbackURL: window.location.href });
      setSent(true);
    } catch (ex) { setErr("Magic link isn't available right now. Use a password below."); setFallback(true); }
    setBusy(false);
  }
  async function password(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setErr("");
    try {
      const r = await auth.signIn.email({ email, password: pw });
      if (r && r.error) throw new Error(r.error.message || "sign in failed");
      window.location.reload();
    } catch {
      try {
        const r2 = await auth.signUp.email({ email, password: pw, name: email });
        if (r2 && r2.error) throw new Error(r2.error.message || "sign up failed");
        window.location.reload();
      } catch (ex2) { setErr(friendly(ex2)); }
    }
    setBusy(false);
  }

  return (
    <div className="grid gap-8 lg:grid-cols-2">
      <div className="card p-8">
        <h2 className="font-display text-2xl text-ink">Sign in to your account</h2>
        <p className="mt-2 text-sm text-ink/70">We send a one-time link to your email. No password to remember.</p>
        {sent ? (
          <div className="mt-6 rounded-lg bg-brand-600/10 p-4 text-sm text-ink">
            <p className="font-semibold">Check your inbox.</p>
            <p className="mt-1">We sent a sign-in link to {email}. Open it on this device and you'll land right back here.</p>
          </div>
        ) : (
          <form className="mt-6 space-y-4" onSubmit={magic}>
            <div>
              <label className={LABEL}>Email address</label>
              <input className={INPUT} type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@company.com" />
            </div>
            <button className="btn w-full" type="submit" disabled={busy}>{busy ? "Sending..." : "Email me a sign-in link"}</button>
          </form>
        )}
        {fallback && (
          <form className="mt-6 space-y-4 border-t border-ink/10 pt-6" onSubmit={password}>
            <p className="text-sm text-ink/70">Or use a password for this account.</p>
            <div>
              <label className={LABEL}>Password</label>
              <input className={INPUT} type="password" required minLength={8} value={pw} onChange={e => setPw(e.target.value)} placeholder="At least 8 characters" />
            </div>
            <button className="btn-secondary w-full" type="submit" disabled={busy}>Continue with password</button>
          </form>
        )}
        {err && <p className="mt-4 text-sm text-red-700">{err}</p>}
        {!fallback && !sent && <button className="mt-4 text-xs font-semibold text-brand-600 underline" onClick={() => setFallback(true)}>Use a password instead</button>}
      </div>
      <div className="card bg-ink p-8 text-white">
        <h3 className="font-display text-2xl">What's inside</h3>
        <ul className="mt-5 space-y-4 text-sm text-white/80">
          <li><span className="font-semibold text-white">Service calls.</span> Every visit we've booked for you, the window we're holding, and the tech assigned.</li>
          <li><span className="font-semibold text-white">Project files.</span> Scope, phase, square footage and the project manager on your build.</li>
          <li><span className="font-semibold text-white">Purchase history.</span> Surge devices, EV chargers, panel upgrades and standby generators you've ordered.</li>
          <li><span className="font-semibold text-white">Site contacts.</span> Gate codes, billing address and how you want us to reach you.</li>
        </ul>
        <p className="mt-8 text-xs text-white/60">Licensed and insured. Serving commercial and estate clients since 2009. Office: Monday to Friday, 7am to 4pm.</p>
      </div>
    </div>
  );
}

export default function App() {
  const [booting, setBooting] = useState(true);
  const [signedIn, setSignedIn] = useState(false);
  const [who, setWho] = useState("");
  const [tab, setTab] = useState("overview");
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState("");
  const [msg, setMsg] = useState("");
  const [calls, setCalls] = useState<Call[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [form, setForm] = useState<any>({ service_type: "Troubleshooting", site_address: "", preferred_date: "", time_window: "morning", urgency: "standard", details: "" });
  const [pform, setPform] = useState<any>({ name: "", site_address: "", scope: "", square_footage: "" });
  const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    setLoading(true); setErr("");
    try {
      const c = await db();
      const [a, b, o, p] = await Promise.all([
        c.from("ce_service_calls").select("*").order("created_at", { ascending: false }),
        c.from("ce_projects").select("*").order("created_at", { ascending: false }),
        c.from("ce_orders").select("*").order("created_at", { ascending: false }),
        c.from("ce_customer_profiles").select("*").limit(1)
      ]);
      if (a.error) throw a.error; if (b.error) throw b.error; if (o.error) throw o.error; if (p.error) throw p.error;
      setCalls(a.data || []); setProjects(b.data || []); setOrders(o.data || []);
      setProfile((p.data && p.data[0]) || null);
    } catch (ex) { setErr(friendly(ex)); }
    setLoading(false);
  }, []);

  useEffect(() => {
    (async () => {
      const t = await freshToken();
      if (t) {
        setSignedIn(true);
        try { const s = await auth.getSession(); const u = s && (s.data ? s.data.user : s.user); if (u && u.email) setWho(u.email); } catch { }
        await load();
      }
      setBooting(false);
    })();
  }, [load]);

  async function bookCall(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setErr(""); setMsg("");
    try {
      const c = await db();
      const row: any = { ...form, preferred_date: form.preferred_date || null };
      const r = await c.from("ce_service_calls").insert(row);
      if (r.error) throw r.error;
      setForm({ service_type: "Troubleshooting", site_address: "", preferred_date: "", time_window: "morning", urgency: "standard", details: "" });
      setMsg("Request received. Dispatch confirms the window by phone within one business day.");
      await load();
    } catch (ex) { setErr(friendly(ex)); }
    setBusy(false);
  }

  async function cancelCall(id: number) {
    setErr(""); setMsg("");
    try {
      const c = await db();
      const r = await c.from("ce_service_calls").delete().eq("id", id);
      if (r.error) throw r.error;
      setMsg("Service call canceled.");
      await load();
    } catch (ex) { setErr(friendly(ex)); }
  }

  async function requestProject(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setErr(""); setMsg("");
    try {
      const c = await db();
      const r = await c.from("ce_projects").insert({ name: pform.name, site_address: pform.site_address, scope: pform.scope, square_footage: pform.square_footage ? Number(pform.square_footage) : null });
      if (r.error) throw r.error;
      setPform({ name: "", site_address: "", scope: "", square_footage: "" });
      setMsg("Estimate request logged. An estimator reviews drawings before we price it.");
      await load();
    } catch (ex) { setErr(friendly(ex)); }
    setBusy(false);
  }

  async function order(sku: string, name: string, price: number) {
    setErr(""); setMsg("");
    try {
      const c = await db();
      const r = await c.from("ce_orders").insert({ item_sku: sku, item_name: name, unit_price: price, install_address: profile ? profile.service_address : "" });
      if (r.error) throw r.error;
      setMsg(name + " added. We'll call to schedule the install date.");
      await load();
    } catch (ex) { setErr(friendly(ex)); }
  }

  async function saveProfile(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setErr(""); setMsg("");
    const p = profile;
    if (!p) { setBusy(false); return; }
    try {
      const c = await db();
      const body = { full_name: p.full_name, email: p.email, phone: p.phone, company: p.company, service_address: p.service_address, city: p.city, state: p.state, postal_code: p.postal_code, preferred_contact: p.preferred_contact, site_access: p.site_access };
      const r = p.visitor_id
        ? await c.from("ce_customer_profiles").update(body).eq("visitor_id", p.visitor_id)
        : await c.from("ce_customer_profiles").insert(body);
      if (r.error) throw r.error;
      setMsg("Contact info saved.");
      await load();
    } catch (ex) { setErr(friendly(ex)); }
    setBusy(false);
  }

  function editProfile(k: string, v: string) {
    const base: any = profile || { visitor_id: "", full_name: "", email: who, phone: "", company: "", service_address: "", city: "", state: "", postal_code: "", preferred_contact: "phone", site_access: "" };
    setProfile({ ...base, [k]: v });
  }

  const spent = orders.reduce((s, o) => s + (Number(o.unit_price) || 0) * (o.quantity || 1), 0);
  const open = calls.filter(c => c.status !== "complete" && c.status !== "closed").length;

  const shell = (kids: React.ReactNode) => (
    <div className="bg-white">
      <section className="bg-ink px-6 py-16 text-white">
        <div className="mx-auto max-w-5xl">
          <p className="text-xs font-semibold uppercase tracking-[0.3em] text-brand-600">C-E ELECTRIC, LLC</p>
          <h1 className="mt-3 font-display text-4xl sm:text-5xl">My Account</h1>
          <p className="mt-4 max-w-xl text-white/70">Your service calls, project files, orders and site contacts in one place.</p>
        </div>
      </section>
      <section className="px-6 py-12"><div className="mx-auto max-w-5xl">{kids}</div></section>
    </div>
  );

  if (booting) return shell(<div className="card p-10 text-center text-ink/60">Checking your session...</div>);
  if (!signedIn) return shell(<SignIn />);

  const t = (id: string, label: string) => (
    <button key={id} onClick={() => setTab(id)} className={tab === id ? "rounded-full bg-brand-600 px-4 py-2 text-sm font-semibold text-white" : "rounded-full bg-ink/5 px-4 py-2 text-sm font-semibold text-ink hover:bg-ink/10"}>{label}</button>
  );

  return shell(
    <div>
      <div className="card mb-6 flex flex-wrap items-center justify-between gap-3 p-5">
        <div>
          <p className="text-xs uppercase tracking-wide text-ink/50">Signed in as</p>
          <p className="font-semibold text-ink">{who || (profile && profile.email) || "your account"}</p>
        </div>
        <button className="btn-secondary" onClick={async () => { try { await auth.signOut(); } catch { } window.location.reload(); }}>Sign out</button>
      </div>

      <div className="mb-6 flex flex-wrap gap-2">
        {t("overview", "Overview")}{t("calls", "Service calls")}{t("projects", "Projects")}{t("orders", "Purchases")}{t("profile", "Contact info")}
      </div>

      {err && <div className="mb-4 rounded-lg bg-red-50 p-4 text-sm text-red-800">{err}</div>}
      {msg && <div className="mb-4 rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800">{msg}</div>}
      {loading && <div className="mb-4 text-sm text-ink/60">Loading your records...</div>}

      {tab === "overview" && (
        <div className="grid gap-5 sm:grid-cols-3">
          <div className="card p-6"><p className="text-xs uppercase tracking-wide text-ink/50">Open service calls</p><p className="mt-2 font-display text-4xl text-ink">{open}</p></div>
          <div className="card p-6"><p className="text-xs uppercase tracking-wide text-ink/50">Active projects</p><p className="mt-2 font-display text-4xl text-ink">{projects.length}</p></div>
          <div className="card p-6"><p className="text-xs uppercase tracking-wide text-ink/50">Ordered to date</p><p className="mt-2 font-display text-4xl text-ink">{money(spent)}</p></div>
          <div className="card p-6 sm:col-span-3">
            <h3 className="font-display text-xl text-ink">Recent activity</h3>
            {calls.length === 0 && orders.length === 0 ? (
              <p className="mt-3 text-sm text-ink/60">Nothing on file yet. Book a service call or order a solution and it shows up here.</p>
            ) : (
              <ul className="mt-4 divide-y divide-ink/10 text-sm">
                {calls.slice(0, 3).map(c => <li key={"c" + c.id} className="flex justify-between py-3"><span className="text-ink">{c.service_type} at {c.site_address || "your site"}</span><Badge text={c.status} /></li>)}
                {orders.slice(0, 3).map(o => <li key={"o" + o.id} className="flex justify-between py-3"><span className="text-ink">{o.item_name}</span><span className="text-ink/60">{money(o.unit_price)}</span></li>)}
              </ul>
            )}
          </div>
        </div>
      )}

      {tab === "calls" && (
        <div className="grid gap-6 lg:grid-cols-2">
          <div className="card p-6">
            <h3 className="font-display text-xl text-ink">Book a service call</h3>
            <form className="mt-4 space-y-4" onSubmit={bookCall}>
              <div><label className={LABEL}>Type of work</label>
                <select className={INPUT} value={form.service_type} onChange={e => setForm({ ...form, service_type: e.target.value })}>
                  <option>Troubleshooting</option><option>Panel or service work</option><option>Lighting</option><option>Generator service</option><option>EV charger</option><option>Tenant improvement punch list</option>
                </select></div>
              <div><label className={LABEL}>Site address</label><input className={INPUT} required value={form.site_address} onChange={e => setForm({ ...form, site_address: e.target.value })} /></div>
              <div className="grid grid-cols-2 gap-3">
                <div><label className={LABEL}>Preferred date</label><input className={INPUT} type="date" value={form.preferred_date} onChange={e => setForm({ ...form, preferred_date: e.target.value })} /></div>
                <div><label className={LABEL}>Window</label>
                  <select className={INPUT} value={form.time_window} onChange={e => setForm({ ...form, time_window: e.target.value })}><option value="morning">7am to 11am</option><option value="afternoon">12pm to 4pm</option><option value="after hours">After hours</option></select></div>
              </div>
              <div><label className={LABEL}>Urgency</label>
                <select className={INPUT} value={form.urgency} onChange={e => setForm({ ...form, urgency: e.target.value })}><option value="standard">Standard</option><option value="priority">Priority, same week</option><option value="emergency">Emergency, power out</option></select></div>
              <div><label className={LABEL}>What's happening</label><textarea className={INPUT} rows={3} value={form.details} onChange={e => setForm({ ...form, details: e.target.value })} placeholder="Breaker trips when the compressor starts." /></div>
              <button className="btn w-full" disabled={busy}>{busy ? "Sending..." : "Request this visit"}</button>
            </form>
          </div>
          <div className="space-y-4">
            {calls.length === 0 ? <div className="card p-6 text-sm text-ink/60">No service calls yet. Book one and dispatch confirms the window.</div> : calls.map(c => (
              <div key={c.id} className="card p-6">
                <div className="flex items-start justify-between gap-3">
                  <div><p className="font-semibold text-ink">{c.service_type}</p><p className="text-sm text-ink/60">{c.site_address}</p></div>
                  <Badge text={c.status} />
                </div>
                <dl className="mt-4 grid grid-cols-2 gap-3 text-sm text-ink/70">
                  <div><dt className="text-xs uppercase text-ink/45">Date</dt><dd>{day(c.preferred_date)}</dd></div>
                  <div><dt className="text-xs uppercase text-ink/45">Window</dt><dd className="capitalize">{c.time_window}</dd></div>
                  <div><dt className="text-xs uppercase text-ink/45">Urgency</dt><dd className="capitalize">{c.urgency}</dd></div>
                  <div><dt className="text-xs uppercase text-ink/45">Tech</dt><dd>{c.technician || "Assigning"}</dd></div>
                </dl>
                {c.details && <p className="mt-3 text-sm text-ink/70">{c.details}</p>}
                <button className="mt-4 text-xs font-semibold text-red-700 underline" onClick={() => cancelCall(c.id)}>Cancel this call</button>
              </div>
            ))}
          </div>
        </div>
      )}

      {tab === "projects" && (
        <div className="grid gap-6 lg:grid-cols-2">
          <div className="card p-6">
            <h3 className="font-display text-xl text-ink">Start a project estimate</h3>
            <p className="mt-2 text-sm text-ink/60">Send the basics. An estimator reviews drawings before we price the work.</p>
            <form className="mt-4 space-y-4" onSubmit={requestProject}>
              <div><label className={LABEL}>Project name</label><input className={INPUT} required value={pform.name} onChange={e => setPform({ ...pform, name: e.target.value })} placeholder="Riverside warehouse fit-out" /></div>
              <div><label className={LABEL}>Site address</label><input className={INPUT} value={pform.site_address} onChange={e => setPform({ ...pform, site_address: e.target.value })} /></div>
              <div><label className={LABEL}>Approx. square footage</label><input className={INPUT} type="number" min="0" value={pform.square_footage} onChange={e => setPform({ ...pform, square_footage: e.target.value })} /></div>
              <div><label className={LABEL}>Scope</label><textarea className={INPUT} rows={4} value={pform.scope} onChange={e => setPform({ ...pform, scope: e.target.value })} placeholder="800A service, 60 lighting fixtures, data rough-in." /></div>
              <button className="btn w-full" disabled={busy}>{busy ? "Sending..." : "Request an estimate"}</button>
            </form>
          </div>
          <div className="space-y-4">
            {projects.length === 0 ? <div className="card p-6 text-sm text-ink/60">No project files yet. Requested estimates and active builds land here.</div> : projects.map(p => (
              <div key={p.id} className="card p-6">
                <div className="flex items-start justify-between gap-3">
                  <div><p className="font-semibold text-ink">{p.name}</p><p className="text-sm text-ink/60">{p.site_address || "Address pending"}</p></div>
                  <Badge text={p.phase} />
                </div>
                <dl className="mt-4 grid grid-cols-2 gap-3 text-sm text-ink/70">
                  <div><dt className="text-xs uppercase text-ink/45">Project manager</dt><dd>{p.project_manager}</dd></div>
                  <div><dt className="text-xs uppercase text-ink/45">Target start</dt><dd>{day(p.target_start)}</dd></div>
                  <div><dt className="text-xs uppercase text-ink/45">Square footage</dt><dd>{p.square_footage ? p.square_footage.toLocaleString() : "Not set"}</dd></div>
                  <div><dt className="text-xs uppercase text-ink/45">Budget</dt><dd>{p.budget_estimate ? money(p.budget_estimate) : "In review"}</dd></div>
                </dl>
                {p.scope && <p className="mt-3 text-sm text-ink/70">{p.scope}</p>}
              </div>
            ))}
          </div>
        </div>
      )}

      {tab === "orders" && (
        <div className="space-y-8">
          <div>
            <h3 className="font-display text-xl text-ink">Electrical solutions</h3>
            <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {CATALOG.map(item => (
                <div key={item.sku} className="card flex flex-col p-5">
                  <p className="font-semibold text-ink">{item.name}</p>
                  <p className="mt-1 flex-1 text-sm text-ink/60">{item.blurb}</p>
                  <p className="mt-3 font-display text-2xl text-ink">{money(item.price)}</p>
                  <button className="btn mt-3" onClick={() => order(item.sku, item.name, item.price)}>Order</button>
                </div>
              ))}
            </div>
          </div>
          <div className="card p-6">
            <h3 className="font-display text-xl text-ink">Purchase history</h3>
            {orders.length === 0 ? <p className="mt-3 text-sm text-ink/60">No purchases on file yet.</p> : (
              <table className="mt-4 w-full text-left text-sm">
                <thead><tr className="text-xs uppercase tracking-wide text-ink/45"><th className="py-2">Item</th><th className="py-2">Ordered</th><th className="py-2">Qty</th><th className="py-2">Total</th><th className="py-2">Status</th></tr></thead>
                <tbody className="divide-y divide-ink/10">
                  {orders.map(o => (
                    <tr key={o.id}><td className="py-3 text-ink">{o.item_name}</td><td className="py-3 text-ink/60">{day(o.created_at)}</td><td className="py-3 text-ink/60">{o.quantity}</td><td className="py-3 text-ink">{money((Number(o.unit_price) || 0) * (o.quantity || 1))}</td><td className="py-3"><Badge text={o.status} /></td></tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      )}

      {tab === "profile" && (
        <form className="card grid gap-4 p-6 sm:grid-cols-2" onSubmit={saveProfile}>
          <div className="sm:col-span-2"><h3 className="font-display text-xl text-ink">Saved contact information</h3><p className="mt-1 text-sm text-ink/60">Our dispatchers use this to reach you and get on site.</p></div>
          <div><label className={LABEL}>Full name</label><input className={INPUT} value={(profile && profile.full_name) || ""} onChange={e => editProfile("full_name", e.target.value)} /></div>
          <div><label className={LABEL}>Company</label><input className={INPUT} value={(profile && profile.company) || ""} onChange={e => editProfile("company", e.target.value)} /></div>
          <div><label className={LABEL}>Email</label><input className={INPUT} type="email" value={(profile && profile.email) || ""} onChange={e => editProfile("email", e.target.value)} /></div>
          <div><label className={LABEL}>Phone</label><input className={INPUT} value={(profile && profile.phone) || ""} onChange={e => editProfile("phone", e.target.value)} /></div>
          <div className="sm:col-span-2"><label className={LABEL}>Service address</label><input className={INPUT} value={(profile && profile.service_address) || ""} onChange={e => editProfile("service_address", e.target.value)} /></div>
          <div><label className={LABEL}>City</label><input className={INPUT} value={(profile && profile.city) || ""} onChange={e => editProfile("city", e.target.value)} /></div>
          <div className="grid grid-cols-2 gap-3">
            <div><label className={LABEL}>State</label><input className={INPUT} value={(profile && profile.state) || ""} onChange={e => editProfile("state", e.target.value)} /></div>
            <div><label className={LABEL}>ZIP</label><input className={INPUT} value={(profile && profile.postal_code) || ""} onChange={e => editProfile("postal_code", e.target.value)} /></div>
          </div>
          <div><label className={LABEL}>Preferred contact</label>
            <select className={INPUT} value={(profile && profile.preferred_contact) || "phone"} onChange={e => editProfile("preferred_contact", e.target.value)}><option value="phone">Phone call</option><option value="text">Text message</option><option value="email">Email</option></select></div>
          <div><label className={LABEL}>Gate code or site access</label><input className={INPUT} value={(profile && profile.site_access) || ""} onChange={e => editProfile("site_access", e.target.value)} placeholder="Gate 2, code 4417, dock open at 7" /></div>
          <div className="sm:col-span-2"><button className="btn" disabled={busy}>{busy ? "Saving..." : "Save contact info"}</button></div>
        </form>
      )}
    </div>
  );
}

createRoot(document.getElementById("tibly-app-root")!).render(<App />);